const GET_USERS="GET_USERS"
const GET_QUESTIONS="GET_QUESTIONS"
const LOGIN="LOGIN"
const LOGOUT="LOGOUT"
const ANSWER_QUESTION="ANSWER_QUESTION"
const GET_MY_QUESTIONS="GET_MY_QUESTIONS"
const SAVE_QUESTION="SAVE_QUESTION"


module.exports={
    GET_QUESTIONS,
    GET_USERS,
    LOGIN,
    ANSWER_QUESTION,
    GET_MY_QUESTIONS,
    LOGOUT,
    SAVE_QUESTION
}